version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_DB: gotothemarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0118
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: