server:
  port: 8080

spring:
  application:
    name: gotothemarket-app

  datasource:
    url: jdbc:postgresql://localhost:5432/gotothemarket
    username: postgres
    password: "0118"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true