server:
  port: 8080

spring:
  application:
    name: gotothemarket-app

  # 프로파일별 설정은 각각의 파일에서 관리
  profiles:
    active: dev #기본적으로 dev 프로파일 사용하기

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.data.jpa.repository.query: INFO
    org.hibernate.internal.AbstractSharedSessionContract: ERROR
    org.hibernate.resource.transaction.backend.jdbc: ERROR
    org.hibernate.orm.sql.ast: WARN